apiVersion: v1
stringData:
  BROKER_HOST: "34.16.96.125"
  DB_HOSTNAME: "192.168.0.3"
  DB_USERNAME: "root"
  DB_PASSWORD: "SHvk8P4~ZVCzC&lP"
  DB_NAME: "ingestas"
  SALUDTECH_ALPES_ADDRESS: "http://sta-service-service"
  
kind: Secret
metadata:
  name: appsecrets